import Link from "next/link";
import { ArrowRight, Check, FileSearch, ScanText, ShieldCheck, Sparkles, LockKeyhole, FileSpreadsheet, GitCompareArrows, TimerReset } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { FaqList } from "@/components/faq-list";
import { MobileCta } from "@/components/mobile-cta";
import { VerifiedReviews } from "@/components/verified-reviews";

export default function Home() {
  return <><SiteHeader/><main itemScope itemType="https://schema.org/SoftwareApplication">
    <meta itemProp="name" content="Foldline"/>
    <meta itemProp="applicationCategory" content="BusinessApplication"/>
    <meta itemProp="operatingSystem" content="Web"/>
    <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow"><span className="liveDot"/>Document workflow, not another OCR demo</span><h1 itemProp="headline">Messy documents in.<br/><em>Trusted data out.</em></h1><p itemProp="description">Foldline extracts invoice data, checks the math, and sends humans only the fields that actually need attention.</p><div className="heroActions"><Link className="button buttonAccent" href="/signup">Process your first document <ArrowRight size={17}/></Link><Link className="button buttonGhost" href="#proof">See Proof Mode</Link></div><div className="trustRow"><span><ShieldCheck size={15}/>Private storage</span><span><Check size={15}/>Evidence-linked fields</span><span><Check size={15}/>Human approval</span></div></div>
    <div className="heroArtifact" aria-label="Illustration of Foldline Proofline review"><div className="paperFold"/><div className="artifactTop"><span>invoice_aug_09.pdf</span><span className="riskPill">12% risk</span></div><div className="artifactBody"><div className="scanPane"><div className="fakeInvoice"><b>ACME SUPPLY LLP</b><p>BIN 123456789012</p><p>Invoice # INV-2048</p><div className="fakeLines"><i/><i/><i/><i/></div><strong>Total ₸ 485,900</strong></div></div><div className="proofPane"><span className="miniLabel">REVIEW BY EXCEPTION</span><div className="proofCard good"><Check size={15}/><div><b>Supplier BIN</b><span>99% confidence</span></div></div><div className="proofCard warn"><Sparkles size={15}/><div><b>VAT</b><span>Needs review · 68%</span></div></div><div className="proofCard good"><Check size={15}/><div><b>Invoice total</b><span>Math reconciled</span></div></div></div></div></div></div></section>

    <section id="how-it-works" className="metricStrip" aria-labelledby="workflow-title"><h2 id="workflow-title" className="srOnly">How Foldline works</h2><div className="container metricGrid"><div><b>01</b><span>Upload</span><p>Private PDF/image ingestion.</p></div><div><b>02</b><span>Parse</span><p>MonkeyOCRv2 reads layout and text.</p></div><div><b>03</b><span>Prove</span><p>Evidence + integrity checks.</p></div><div><b>04</b><span>Export</span><p>Approved data becomes CSV.</p></div></div></section>

    <section id="proof" className="featureSection"><div className="container split"><div><span className="eyebrow">The killer feature</span><h2>Proofline: review only what can hurt you.</h2><p>Most OCR products stop at extraction. Foldline adds a trust layer: confidence, source evidence and deterministic financial checks before data leaves the workspace.</p><ul className="featureList"><li><FileSearch/>Every value keeps its evidence snippet.</li><li><ScanText/>Subtotal + VAT + line items are reconciled automatically.</li><li><Sparkles/>Low-confidence fields become a focused exception queue.</li></ul><Link href="/use-cases" className="inlineLink">Explore document workflows <ArrowRight size={15}/></Link></div><div className="proofDemo"><div className="proofDemoHeader"><span>Exceptions</span><b>2 of 14 fields</b></div><div className="exceptionCard"><span className="riskDot"/><div><b>VAT amount</b><p>OCR says ₸ 51,420 · calculated expectation ₸ 48,590</p><small>Evidence: “НДС 12% — 51 420,00”</small></div></div><div className="exceptionCard"><span className="warnDot"/><div><b>Supplier name</b><p>58% confidence · confirm before export</p><small>Evidence: “ACME SUPPLY LLP”</small></div></div><div className="allGood"><Check/>12 fields passed automatically</div></div></div></section>

    <section className="workflowSection"><div className="container"><div className="sectionIntro"><span className="eyebrow">Built for the whole workflow</span><h2>Extraction is infrastructure. Trust is the product.</h2><p>Foldline is intentionally designed around the expensive part: deciding whether machine-extracted data is safe to use.</p></div><div className="workflowCards"><article><FileSpreadsheet/><span>Invoice extraction</span><h3>From document to structured fields.</h3><p>Supplier, identifiers, dates, line items, VAT and total are mapped into a stable schema.</p></article><article><GitCompareArrows/><span>Proofline</span><h3>Compare values against the document and the math.</h3><p>Source evidence and reconciliation checks reduce blind trust in OCR output.</p></article><article><TimerReset/><span>Status clarity</span><h3>No mystery spinner.</h3><p>Uploads move through explicit states: verified, queued, processing, ready or failed—with safe retry when needed.</p></article></div></div></section>

    <section id="security" className="securityBand"><div className="container split"><div className="securityVisual"><LockKeyhole size={35}/><strong>Private by default</strong><span>R2 signed access · RLS isolation · server-only secrets</span></div><div><span className="eyebrow">Security</span><h2>Documents never need to become public URLs.</h2><p>Foldline’s deployment architecture uses private object storage, short-lived signed access and database policies that isolate each user’s records.</p><Link href="/security" className="inlineLink">Read the security architecture <ArrowRight size={15}/></Link></div></div></section>

    <section id="faq" className="faqSection"><div className="container split faqSplit"><div><span className="eyebrow">FAQ</span><h2>Before you upload the first invoice.</h2><p>Six practical answers about what the MVP does, where documents go, and what still requires human judgment.</p></div><FaqList/></div></section>

    <VerifiedReviews/>

    <section className="ctaSection"><div className="container ctaCard"><div><span className="eyebrow">MVP v0.1</span><h2>Make the first ten invoices boring.</h2><p>That is the goal: reliable enough that extracting an invoice stops feeling like a task.</p></div><Link href="/signup" className="button buttonAccent">Start free <ArrowRight size={17}/></Link></div></section>
  </main><footer className="footer"><div className="container"><span>© 2026 Foldline</span><div><Link href="/use-cases">Use cases</Link><Link href="/case-studies">Case studies</Link><Link href="/security">Security</Link><Link href="/pricing">Pricing</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link></div></div></footer><MobileCta/></>;
}
