import Link from "next/link";
import { ArrowRight, Check, FileSearch, ScanText, ShieldCheck, LockKeyhole, FileSpreadsheet, GitCompareArrows, TimerReset } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { FaqList } from "@/components/faq-list";
import { MobileCta } from "@/components/mobile-cta";
import { VerifiedReviews } from "@/components/verified-reviews";

export default function Home() {
  return <><SiteHeader/><main itemScope itemType="https://schema.org/SoftwareApplication">
    <meta itemProp="name" content="Foldline"/>
    <meta itemProp="applicationCategory" content="BusinessApplication"/>
    <meta itemProp="operatingSystem" content="Web"/>

    <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow"><span className="liveDot"/>Invoice review for early pilots</span><h1 itemProp="headline">Review only what<br/><em>can hurt you.</em></h1><p itemProp="description">Foldline extracts invoice fields, checks totals and references, and keeps source evidence next to anything that needs a human review.</p><div className="heroActions"><Link className="button buttonAccent" href="/signup">Review an invoice <ArrowRight size={17}/></Link><Link className="button buttonGhost" href="/contact">Request a pilot</Link></div><div className="trustRow"><span><ShieldCheck size={15}/>Private storage</span><span><Check size={15}/>Evidence-linked fields</span><span><Check size={15}/>Human approval</span></div></div>
    <div className="heroArtifact" aria-label="Illustration of Foldline invoice review"><div className="paperFold"/><div className="artifactTop"><span>invoice_aug_09.pdf</span><span className="riskPill">12% risk</span></div><div className="artifactBody"><div className="scanPane"><div className="fakeInvoice"><b>ACME SUPPLY LLP</b><p>BIN 123456789012</p><p>Invoice # INV-2048</p><div className="fakeLines"><i/><i/><i/><i/></div><strong>Total ₸ 485,900</strong></div></div><div className="proofPane"><span className="miniLabel">REVIEW BY EXCEPTION</span><div className="proofCard good"><Check size={15}/><div><b>Invoice total</b><span>Math reconciled</span></div></div><div className="proofCard warn"><FileSearch size={15}/><div><b>PO number</b><span>Needs review</span></div></div><div className="proofCard good"><Check size={15}/><div><b>Invoice number</b><span>No duplicate found</span></div></div></div></div></div></div></section>

    <section id="how-it-works" className="metricStrip" aria-labelledby="workflow-title"><h2 id="workflow-title" className="srOnly">How Foldline works</h2><div className="container metricGrid"><div><b>01</b><span>Upload</span><p>Add a PDF or image privately.</p></div><div><b>02</b><span>Extract</span><p>Foldline turns the document into structured fields.</p></div><div><b>03</b><span>Check</span><p>Totals, references and confidence are checked.</p></div><div><b>04</b><span>Review</span><p>You focus on the exceptions and evidence.</p></div></div></section>

    <section id="proof" className="featureSection"><div className="container split"><div><span className="eyebrow">Proofline</span><h2>Review only what can hurt you.</h2><p>Extraction is only the first step. Foldline keeps the original evidence beside the extracted result and highlights the places that deserve a second look.</p><ul className="featureList"><li><FileSearch/>Every extracted value can keep its source snippet.</li><li><ScanText/>Subtotal, VAT and line-item arithmetic are checked.</li><li><GitCompareArrows/>Missing or duplicate invoice references can be flagged for review.</li></ul><Link href="/contact" className="inlineLink">Bring a real workflow to the pilot <ArrowRight size={15}/></Link></div><div className="proofDemo"><div className="proofDemoHeader"><span>Exceptions</span><b>2 fields</b></div><div className="exceptionCard"><span className="riskDot"/><div><b>Total mismatch</b><p>Subtotal + VAT does not match the invoice total.</p><small>Evidence remains attached to the extracted values.</small></div></div><div className="exceptionCard"><span className="warnDot"/><div><b>PO reference</b><p>No PO number was detected.</p><small>Confirm whether this invoice requires one.</small></div></div><div className="allGood"><Check/>Other checked fields passed</div></div></div></section>

    <section className="workflowSection"><div className="container"><div className="sectionIntro"><span className="eyebrow">What the MVP does today</span><h2>Invoice review first. Broader document workflows later.</h2><p>The current product is intentionally narrow while the first real workflows are being validated.</p></div><div className="workflowCards"><article><FileSpreadsheet/><span>Invoice extraction</span><h3>From document to structured fields.</h3><p>Supplier, identifiers, dates, line items, VAT and totals are extracted into a reviewable schema.</p></article><article><GitCompareArrows/><span>Checks</span><h3>Catch arithmetic and reference problems.</h3><p>Foldline checks invoice math, missing references and duplicate invoice numbers without claiming to replace human review.</p></article><article><TimerReset/><span>Clear status</span><h3>No mystery spinner.</h3><p>Uploads move through explicit processing states and can be retried safely when something fails.</p></article></div></div></section>

    <section id="security" className="securityBand"><div className="container split"><div className="securityVisual"><LockKeyhole size={35}/><strong>Private by default</strong><span>Supabase private storage · RLS isolation · server-only secrets</span></div><div><span className="eyebrow">Security</span><h2>Uploaded documents are not public files.</h2><p>Foldline uses private storage, short-lived signed access and database policies to keep document access scoped to the right account and workflow.</p><Link href="/security" className="inlineLink">Read the security architecture <ArrowRight size={15}/></Link></div></div></section>

    <section id="faq" className="faqSection"><div className="container split faqSplit"><div><span className="eyebrow">FAQ</span><h2>Before you upload the first invoice.</h2><p>Practical answers about what the current MVP does, where documents go, and what still requires human judgment.</p></div><FaqList/></div></section>

    <VerifiedReviews/>

    <section className="ctaSection"><div className="container ctaCard"><div><span className="eyebrow">Early pilot</span><h2>Have a workflow that still depends on manual checking?</h2><p>Tell me what your team reviews today and we can see whether Foldline is a reasonable fit.</p></div><Link href="/contact" className="button buttonAccent">Request a pilot <ArrowRight size={17}/></Link></div></section>
  </main><footer className="footer"><div className="container"><span>© 2026 Foldline</span><div><Link href="/contact">Contact</Link><Link href="/use-cases">Use cases</Link><Link href="/security">Security</Link><Link href="/pricing">Pricing</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link></div></div></footer><MobileCta/></>;
}
